% Jun-Yan Zhu (junyanz at eecs dot berkeley dot edu)
% University of California, Berkeley
% a script to download portrait data from the Gallagher Collection Person Dataset
% (http://chenlab.ece.cornell.edu/people/Andy/GallagherDataset.html)
% See the first row of Figure 17 for details. 

%% get image urls and bounding boxes
SetPaths;
load('demo_download.mat', 'imgList', 'imgURLs', 'bboxes');
nImgs = numel(imgList);

imgFold_o = 'data/demo/imgs_o';  % original images
imgFold = 'data/demo/imgs';      % cropped faces
mkdirs({imgFold_o, imgFold});

disp('install the Gallagher Collection Person Dataset'); 
parfor n = 1 : nImgs
    name = imgList{n}; 
    impath = fullfile(imgFold_o, name);
    if ~exist(impath, 'file') 
        im = imread(imgURLs{n});
        fprintf('download image (%s)\n', name); 
        imwrite(im, impath);
    end
end

%% crop faces using the pre-computed bounding boxes 
% The face bounding boxes are generated by Viola-Jones Face detector
% http://www.mathworks.com/help/vision/ref/vision.cascadeobjectdetector-class.html
disp('crop faces'); 
for n = 1 : nImgs
    im = imread(fullfile(imgFold_o, imgList{n})); 
    crop = ImCropPad(im, bboxes{n}); 
    crop = imresize(crop, [250, 250]); 
    imwrite(crop, fullfile(imgFold, imgList{n})); 
end

